stages:
- name: Construct and Publish Image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: jorinl/pxe-tftp:pxe-tftpv.1
      pushRemote: true
      registry: index.docker.io
timeout: 60
